### ISSUE TITLE
Lock control to particular media player

### ISSUE THREAD

**Issue by geo242** [BlackDex/mpris-control#1]
Is there a way to specify which application should be controlled? I discovered this need when wanted to control spotify but had youtube open in chrome and the application would only control youtube. As soon as I closed the tab, control went back to spotify.

**Comment by BlackDex** [comment]
That is a good one.
I have to look in to that.

**Comment by BlackDex** [comment]
It seems it could be possible, i have to look in to this and see when i have some time to test this.

**Comment by BlackDex** [comment]
@geo242 thanks to @treeshateorcs this is added.
I Also made it possible to trigger multiple or all players instead of just only one.
