### ISSUE TITLE
D-Bus call failed

### ISSUE THREAD

**Issue by ghost** [BlackDex/mpris-control#4]
Sometimes I receive this error message for an unknown reason

>"Could not find any player: D-Bus call failed: \"Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.\""

only reboot helps

**Comment by BlackDex** [comment]
I Think i see some other issues also.
Will look into it.

**Comment by BlackDex** [comment]
btw, that error could also indicate that d-bus has some issues. which i had a long time ago.
Restarting/Reloading dbus sometimes helped.

**Comment by ghost** [comment]
no, d-bus works alright, because playerctl does

**Comment by BlackDex** [comment]
The next time you see this happen, could you run `dbus-monitor` and just try a `list` or something?
This error does implicate that it is an error in the mpris-rs library, but maybe we could figure it out.

**Comment by ghost** [comment]
sure, i will let you know

**Comment by ghost** [comment]
btw, you can shorten any command, so instead of writing `mpris-control toggle` you can write `mpris-control tog` or even `mpris-control t`

**Comment by BlackDex** [comment]
I Just released a new version with an updated dbus dependency.
Since this issue is open a long time, and apparently nothing happened again i will close this now.
Please open a new one in case it also happens with the latest version.
